<a href="https://colab.research.google.com/github/LEANA18/Machine-Learning/blob/main/NumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1=[10,20,30]
print(list1)

[10, 20, 30]


In [3]:
np.array(list1)

array([10, 20, 30])

In [4]:
list2=[10,20,"30"]
np.array(list2)

array(['10', '20', '30'], dtype='<U21')

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [7]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [8]:
x[2]="xyz"

ValueError: could not convert string to float: 'xyz'

In [9]:
x1=np.zeros(10)
x1.dtype

dtype('float64')

In [10]:
y1=np.zeros(10,int)
y1.dtype

dtype('int64')