In [1]:
import numpy as np
import math as m

In [2]:
x=[1,2,3]
y=[4,5,6]
x=x+10

TypeError: can only concatenate list (not "int") to list

In [9]:
x=np.array([1,2,3])
y=np.array([3,5,6])
x=x+10
print(x)

[11 12 13]


In [10]:
print(x+y)

[14 17 19]


In [11]:
z=np.array([100,200,300,400])
print(y+z)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [12]:
print(x*2)

[22 24 26]


In [13]:
print(x*y)

[33 60 78]


In [14]:
print(x**3)

[1331 1728 2197]


In [15]:
print(x.mean())

12.0


In [16]:
print(x.sum())

36


In [17]:
p1=np.array([2,2,2])
p2=np.array([1,1,1])
val=((p1-p2)**2)
print(val)

[1 1 1]


In [18]:
val2=val.sum()
print(val2)

3


In [19]:
m.sqrt(val2)

1.7320508075688772

In [26]:
#Above can be also done like this
val3=((p1-p2)**2).sum()
print(val3)
m.sqrt(val3)

3


1.7320508075688772

In [25]:
#Average of points
pts=np.array([4,5,6,7])
value=((pts-pts.mean())**2).sum()
print(value)
m.sqrt(value)

5.0


2.23606797749979

In [28]:
m1=np.array([1,2,3])
m2=np.array([4,5,6])
print(m1.dot(m2))
print(m2.dot(m1))

32
32
