In [1]:
import numpy as np

In [3]:
#2D array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
x5=np.ones(5)
x5[3]=2
print(x5)

[1. 1. 1. 2. 1.]


In [5]:
x5[3]="2"
print(x5)

[1. 1. 1. 2. 1.]


In [6]:
x5[2]="as"
print(x5)

ValueError: could not convert string to float: 'as'

In [8]:
#3D array
ThreeD_array=np.zeros((3,4,5))
print(ThreeD_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [9]:
ThreeD_array[0][1][2]

0.0

In [10]:
ThreeD_array[0][1]

array([0., 0., 0., 0., 0.])

In [11]:
ThreeD_array[0]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
ThreeD_array.shape

(3, 4, 5)

In [13]:
a=np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

In [15]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(twoD_array[1])

[4 5 6]


In [17]:
print(twoD_array[2])

[7 8 9]


In [18]:
print(twoD_array[1:3])

[[4 5 6]
 [7 8 9]]


In [19]:
print(twoD_array[:,1])

[2 5 8]


In [20]:
new_twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_twoD_array[1:3,0]

array([4, 7])

In [21]:
new_twoD_array[1:3,0:2]

array([[4, 5],
       [7, 8]])